apiVersion : apps/v1
kind: Deployment
metadata:
  name: "hitech-252d"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "hitech-252d"
  template:
    metadata:
      labels:
        app: "hitech-252d"
    spec:
      containers:
        - name: "hitech-252d"
          image: "lkhitech2.azurecr.io/hitech"
          ports:
          - containerPort: 80