apiVersion: v1
kind: Service
metadata:
    name: "cs-9254"
    labels:
        app: "cs-9254"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "cs-9254"